### ISSUE TITLE
Getting an error while running

### ISSUE THREAD

**Issue by yg** [plibither8/gh-followers-tracker#1]
I configured all tokens

![Screenshot](https://user-images.githubusercontent.com/61746440/82124823-3f041000-97bf-11ea-9f86-8a7daefe312c.png)

https://github.com/yg/gh-followers-tracker

**Comment by yg** [comment]
Fixed after updating the gist name and its content.

Thanks for making this action!

**Comment by plibither8** [comment]
Hi! I was just about to type down the possible cause (name issue only :D).
Thanks for creating the issue and using it :)

Also, I took a look at your repo: you might want to change the `notify()` function's content (if you haven't already) as per your preferred method of notification.

Cheers!

**Comment by yg** [comment]
I'm not getting Telegram Notification @plibither8 :rocket:

**Comment by yg** [comment]
@plibither8 Do you get telegram notifications? I don't get it :cry:
