### ISSUE TITLE
Convert to a template?

### ISSUE THREAD

**Issue by AnandChowdhary** [plibither8/gh-followers-tracker#3]
I'd love to use this repo, maybe it's better to convert this to a template so I can click on the "Use this template" button rather than forking it?

[Because contributions don't count in forks](https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile)

**Comment by plibither8** [comment]
Great idea! I'll try to implement this tomorrow morning, thanks! :D

**Comment by plibither8** [comment]
Done... That was simple enough xD
